# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  callbacks: []
  max_epochs: 50

data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 8
    check_stackability: False
    num_workers: 8
    num_classes: 2
    img_grep: "*_embedding.tif"
    label_grep: "*.mask.tif"
    no_label_replace: -1
    embedding_input: True

    train_split: hls_burn_scars/splits/train.txt
    val_split: hls_burn_scars/splits/val.txt
    test_split: hls_burn_scars/splits/test.txt

    train_data_root: hls_burn_scars/embeddings_terramind/layer_00
    train_label_data_root: hls_burn_scars/data
    val_data_root: hls_burn_scars/embeddings_terramind/layer_00
    val_label_data_root: hls_burn_scars/data
    test_data_root: hls_burn_scars/embeddings_terramind/layer_00
    test_label_data_root: hls_burn_scars/data

    train_transform:
      - class_path: albumentations.D4
      - class_path: albumentations.pytorch.ToTensorV2

predict_output_dir: './'

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: IdentityBackbone
      backbone_out_channels: [384]
      necks:
        - name: SelectIndices
          indices: [0]
      decoder: FCNDecoder
      decoder_channels: 32
      head_dropout: 0.1
      head_channel_list: [32]
      num_classes: 2
      rescale: false
      image_size_out: [512,512]
    loss: dice
    ignore_index: -1
    freeze_backbone: true
    freeze_decoder: false

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.e-4
    weight_decay: 0.1
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
    factor: 0.5
    patience: 5
