# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  num_sanity_val_steps: 0
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  logger: true
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    

  max_epochs: 50
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true

data:
  class_path: GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 8
    num_workers: 8
    constant_scale: 0.0001
    dataset_bands:
      - COASTAL_AEROSOL
      - BLUE
      - GREEN
      - RED
      - RED_EDGE_1
      - RED_EDGE_2
      - RED_EDGE_3
      - NIR_BROAD
      - NIR_NARROW
      - WATER_VAPOR
      - CIRRUS
      - SWIR_1
      - SWIR_2
    output_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    rgb_indices:
      - 2
      - 1
      - 0
    train_data_root: sen1floods11_v1.1/data/S2L1CHand
    train_label_data_root: sen1floods11_v1.1/data/LabelHand
    val_data_root: sen1floods11_v1.1/data/S2L1CHand
    val_label_data_root: sen1floods11_v1.1/data/LabelHand
    test_data_root: sen1floods11_v1.1/data/S2L1CHand
    test_label_data_root: sen1floods11_v1.1/data/LabelHand
    train_split: sen1floods11_v1.1/splits/flood_train_data.txt
    test_split: sen1floods11_v1.1/splits/flood_test_data.txt
    val_split: sen1floods11_v1.1/splits/flood_valid_data.txt

    img_grep: "*_S2Hand.tif"
    label_grep: "*_LabelHand.tif"
    no_label_replace: -1
    no_data_replace: 0
    means:
      - 0.1412956
      - 0.13795798
      - 0.12353792
      - 0.30902815
      - 0.2044958
      - 0.11912015
    stds:
      - 0.07406382
      - 0.07370365
      - 0.08692279
      - 0.11798815
      - 0.09772074
      - 0.07659938
    num_classes: 2
    # train_transform:
    #   - class_path: albumentations.RandomCrop
    #     init_args:
    #         height: 224
    #         width: 224
    #   - class_path: albumentations.HorizontalFlip
    #     init_args:
    #         p: 0.5
    #   - class_path: ToTensorV2
    # val_transform:
    #   - class_path: albumentations.CenterCrop
    #     init_args:
    #         height: 224
    #         width: 224
    #   - class_path: ToTensorV2
    # test_transform:
    #   - class_path: albumentations.CenterCrop
    #     init_args:
    #         height: 224
    #         width: 224
    #   - class_path: ToTensorV2

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_args:
      decoder: FCNDecoder
      backbone_pretrained: True
      backbone_img_size: 512
      backbone: dofa_base_patch16_224
      decoder_channels: 256
      backbone_model_bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2

      num_classes: 2
      head_dropout: 0.1
      head_channel_list:
        - 256
      necks:
        - name: SelectIndices
          indices:
            - -1
        - name: ReshapeTokensToImage
    loss: ce
    
    ignore_index: -1
    class_weights:
      - 0.3
      - 0.7
    freeze_backbone: false
    freeze_decoder: false
    model_factory: EncoderDecoderFactory
    tiled_inference_parameters:
      h_crop: 224
      h_stride: 196
      w_crop: 224
      w_stride: 196
      average_patches: true
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 6.e-5
    weight_decay: 0.05
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss